# Before Bonus
# Vagrant.configure("2") do |config|
#   config.vm.box = "devops-boxes/ubuntu-focal-docker-virtualization-challenge"
#   config.vm.box_version = "1.1.0"
#   config.vm.boot_timeout = 600

#   config.vm.provider "virtualbox" do |vb|
#     vb.name = "docker-basics-challenge"
#     vb.memory = "2048"
#     vb.cpus = 2
#   end

#   config.vm.provision "shell", inline: <<-SHELL
#     sudo apt-get update
#     sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

 #    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

#     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

#     sudo apt-get update
#     sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

#     sudo usermod -aG docker vagrant
#   SHELL
# end

# After Bonus
Vagrant.configure("2") do |config|
  config.vm.box = "devops-boxes/ubuntu-focal-docker-virtualization-challenge"
  config.vm.box_version = "1.1.0"
  config.vm.boot_timeout = 600

  config.vm.synced_folder "../03-docker-advance-concepts", "/challenge3"
  config.vm.synced_folder "../04-cicd", "/challenge4"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-basics-box-test"
    vb.memory = "2048"
    vb.cpus = 2
  end
end

